export const content = [
  {
    id: 1,
    title: "Advanced Arthritis Panel",
    tests: [
      "CBC",
      "Uric Acid",
      "Calcium",
      "RA Factor",
      "CRP",
      "Vit D3",
      "X-Ray Double View",
    ],
    price: 3750,
    offerPrice: 1900,
  },
  {
    id: 2,
    title: "Basic Arthritis Panel",
    tests: ["CBC", "Uric Acid", "Calcium", "RA Factor", "CRP"],
    price: 1690,
    offerPrice: 800,
  },
  {
    id: 3,
    title: "Basic Fever Panel",
    tests: ["CBC + ESR", "MP", "Widal", "Urinal R/M"],
    price: 1190,
    offerPrice: 666,
  },
  {
    id: 4,
    title: "Advanced Basic Fever Panel",
    tests: [
      "CBC + ESR",
      "MP",
      "Widal",
      "Urinal R/M",
      "Typhoidal",
      "Dengue Combo",
    ],
    price: 2560,
    offerPrice: 1500,
  },
  {
    id: 5,
    title: "Advanced Basic Fever Panel",
    tests: [
      "CBC (Complete Blood Count)",
      "TFT (Thyroid Function Test/ Thyroid Profile)",
      "LH (Luteinizing Hormone)",
      "FSH (Follicile Stimulating Hormone)",
      "Prolectin",
      "Urine R/M",
    ],
    price: 2500,
    offerPrice: 1200,
  },
  {
    id: 6,
    title: "Diabetes Care Packages",
    tests: ["FBS", "PPBS", "HbA1C"],
    price: 670,
    offerPrice: 350,
  },
  {
    id: 7,
    title: "Basic Diabetes Care Packages",
    tests: ["FBS", "PPBS", "HbA1C", "Lipid Profile", "Creatinine", "Urea"],
    price: 1520,
    offerPrice: 888,
  },
  {
    id: 8,
    title: "Advanced Diabetes Care Packages",
    tests: [
      "FBS",
      "PPBS",
      "HbA1C",
      "Lipid Profile",
      "CBC",
      "LFT",
      "KFT",
      "Urine",
    ],
    price: 4470,
    offerPrice: 2700,
  },
];
