export const tests = [
  {
    id: 1,
    title: "COMPLETE BLOOD COUNT; CBC",
    params: 22,
    price: 350,
    home: true,
  },
  {
    id: 2,
    title: "Ashish; CBC",
    params: 22,
    price: 350,
    home: false,
  },
  {
    id: 3,
    title: "COMPLETE BLOOD COUNT; CBC",
    params: 22,
    price: 350,
    home: true,
  },
  {
    id: 4,
    title: "COMPLETE BLOOD COUNT; CBC",
    params: 22,
    price: 350,
    home: true,
  },
  {
    id: 5,
    title: "COMPLETE BLOOD COUNT; CBC",
    params: 22,
    price: 350,
    home: true,
  },
  {
    id: 6,
    title: "COMPLETE BLOOD COUNT; CBC",
    params: 22,
    price: 350,
    home: true,
  },
  {
    id: 7,
    title: "COMPLETE BLOOD COUNT; CBC",
    params: 22,
    price: 350,
    home: false,
  },
];
